
add_newline = false 
format = "$directory$hostname$git_status$git_branch$git_state"

[directory]
truncation_length = 1
style = "cyan"
format = " â¤ [$path]($style)[$read_only]($read_only_style) â¤ "

[hostname]
ssh_only = true
format = "[$hostname](yellow) â¤ "

[git_branch]
style = "cyan"
symbol = "îœ¥"
format = "[$symbol\\(]($style)[$branch](white)[\\)]($style)â¤ "

[git_status]
ahead = "[ï‚ª${count}](green)"
behind = "[ï‚«${count}](red)"
diverged = "[ï‚²Diverged](red)"
staged = "[ï˜±${count}](green) "
untracked = "[ï‘¨${count}](red)"
modified = "[îœ¨${count}](red)"
renamed = "[ïƒ¬${count}(yellow)]"
deleted = "[ï€”{count}](red)"
conflicted = "[ï‚²Conflicted](red)"
style = "#E29257"
format = "[$ahead$behind$diverged$staged$untracked$modified$renamed$deleted$conflicted](#E29257)"

[git_state]
style = "#E29257"
format = '[\($state( $progress_current of $progress_total)\)]($style)'
cherry_pick = "[ğŸ’ PICKING](bold red)"


